[package]
name = "mpc-channel-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
md5 = "0.7.0"
syn = { version = "1.0.99"}
quote = "1.0.21"
proc-macro2 = "1.0.43"